version: 0.1

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew test
      - ./gradlew assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
